---
name: test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: ./
      - name: Test a single file
        uses: ./
        with:
          config_file_path: tests/renovate-test.json
      - name: Test multiple files
        uses: ./
        with:
          config_file_path: |
            tests/renovate-test.json
            tests/renovate.json
      - id: files
        run: |
          set -euo pipefail
          files=$(git ls-files | grep renovate.json)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          {
            echo "files<<$EOF"
            echo "$files"
            echo "$EOF"
          } >> "$GITHUB_OUTPUT"
      - name: Pass files through output
        uses: ./
        with:
          config_file_path: ${{ steps.files.outputs.files }}
